import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import Filter from '@/components/Filter';
const inter = Inter({ subsets: ['latin'] });
import axios from 'axios';
import MovieList from '@/components/MovieList';
import SidebarTwo from '@/components/SidebarTwo';
import PopularMovies from '@/components/PopularMovies';

import { useEffect, useState } from 'react';

const Home = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div className="flex flex-row">
          <div className="w-full h-screen px-4 py-8 bg-slate-100 ">
            <Filter />
            <div className="flex items-center justify-between">
              <h1 className="text-xl font-medium">Popular Movies</h1>
              <Link href="/popular">See All</Link>
            </div>
            <PopularMovies />
            {/* <MovieList data={data} /> */}
          </div>
          <div className="w-56 px-4 py-8 overflow-hidden ">
            <p>Lorem ipsum dolor sit amet consectetur.</p>
            {/* <SidebarTwo /> */}
          </div>
        </div>
      </main>
    </>
  );
};
export async function getServerSideProps() {
  try {
    const response = await axios.get(
      'https://api.themoviedb.org/3/discover/movie',
      // 'https://api.themoviedb.org/3/search/multi',
      {
        params: {
          api_key: process.env.NEXT_PUBLIC_TMDB_API,
          // query: 'Batman', // Replace 'Batman' with your desired search query
        },
      }
    );

    const data = response.data.results || [];

    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.error('Error fetching data:', error.message);
    return {
      props: {
        data: [],
      },
    };
  }
}
export default Home;
